[package]
name = "unsplashwalp"
version = "0.1.0"
authors = ["adeyahya <adeyahyaprasetyo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wallpaper = "2.0.1"
regex = "1.3.6"
